jser/jser.github.io

_posts/2015/2015-02-15-browsersync.md, _posts/2015/2015-02-16-6to5-to-babel-browsersync-flux.md
Pull Request方式で記事を書いて見るテストです。
- [Asynchronous Programming: The End of The Loop - Video Tutorial Series @eggheadio](https://egghead.io/series/mastering-asynchronous-programming-the-end-of-the-loop "Asynchronous Programming: The End of The Loop - Video Tutorial Series @eggheadio")
- NetflixのJafar Husainさん というフレーズを使う
----
- Pull Request をマージ => 記事の公開というのをやりたい
- ヘッドラインで選ぶ記事を公開時にその場で書くのより、少しずつやりたい時がある
- 書き途中で他の人が介入できる
- GitHub上でのみ記事を書く試みの一環
- 今複数の環境で色々やってるのでローカルで同期するのがとても面倒くさくて直接Webでやりたい感じ。
ACE Editorはさすがに辛いので、ACEと同期するtextareaを置いて、これをViewSourceWithみたいなやつで編集してる。
- [add placeholder textarea which sync with ACE Editor to GitHub.](https://gist.github.com/azu/90863c5082dd81a49fa4 "add placeholder textarea which sync with ACE Editor to GitHub.")
=> 2015-02-16のJavaScript

_posts/2015/2015-03-02-firefox36-ast-serviceworker.md, _posts/2015/2015-03-02-title.md
この記事から[SpellCheck](https://github.com/jser/jser.github.io/blob/master/CONTRIBUTING.md "SpellCheck")が入ってる
=> write(post): 2015-03-02のJS

_posts/2015/2015-03-02-ie-rxjs-chrome-devtools.md
- [Rendering engine updates in March for the Windows 10 Technical Preview - IEBlog - Site Home - MSDN Blogs](http://blogs.msdn.com/b/ie/archive/2015/03/18/rendering-engine-updates-in-march-for-the-windows-10-technical-preview.aspx)
- [「RxJS」初心者入門 - JavaScriptの非同期処理の常識を変えるライブラリ | 株式会社LIG](http://liginc.co.jp/web/js/151272)
- [DevTools: State Of The Union 2015 // Speaker Deck](https://speakerdeck.com/addyosmani/devtools-state-of-the-union-2015)
=> 2015-03-23のJS

_posts/2015/2015-05-04-iojs2.0.0-msedge-isomorphic.md, _posts/2015/2015-05-04-title.md
- [io.js の v2.0 が出ました。 - from scratch](http://yosuke-furukawa.hatenablog.com/entry/2015/05/06/170034 "io.js の v2.0 が出ました。 - from scratch")
=> post: 2015-05-06 # 226

_posts/2015/2015-05-03-title.md
=> 2015-05-12のJS

_posts/2015/2015-06-02-Angular1.4.0-Polymer1.0-.md
=> 2015-06-02のJavaScript

.travis.yml, Gemfile, Gemfile.lock, Rakefile
Use [jirutka/rake-jekyll](https://github.com/jirutka/rake-jekyll "jirutka/rake-jekyll")
As a resuit : 
push to `master`, then Travis CI push to `gh-pages`
This pull request is part of #83
=> Integrate Travis CI deploy

.travis.yml, Gemfile.lock, _i18n/ja/_posts/2014/2014-08-03-renewal.md, _includes/edit-on-github.html, _includes/see-revision-on-github.html, _layouts/post.html, test/rules/spellcheck-post.js, test/travis-spellcheck.sh
As a part of https://github.com/jser/jser.github.io/issues/83
=> fix: rename "master" to "develop" branch

_i18n/ko/_posts/2015/2015-05-27-promise-angular2.md, _i18n/ko/_posts/2015/2015-06-02-Angular1.4.0-Polymer1.0.md
azuさま、
ジョウンです。
UYEONGさんの紹介により翻訳に参加することになりました。
宜しくお願い申し上げます。
６月２日のアティクールの翻訳本です。
=> 「韓国語翻訳」６月２日の2015-06-02 JS: AngularJS 1.4.0、Polymer 1.0の翻訳

_i18n/ja.yml, _i18n/ja/about.md, _i18n/ko.yml, _i18n/ko/about.md, _includes/sidebar.html, _layouts/page.html, about.md
=> feat(translate): about.html translated into korean

_i18n/ko/_posts/2015/2015-06-10-es6-status-webaudio.md
=> translate to korean @2015-06-10

_i18n/ko/_posts/2015/2015-04-20-es6-final-draft-js-traning.md
2015年4月20日のアーティクルに対する韓国語翻訳機です。
=> 2015-04-20 es6 final draft js training

_i18n/ko/_posts/2015/2015-06-23-es6-svg-jsconfus.md
６月の２３日の記事の翻訳本です。
６月の１７日の分は＠UYEONGさんが翻訳してます。
ありがとうございます。
=> translate to korean 2015-06-23

_i18n/ja/_posts/2015/2015-07-11-jshint-new-lang-features.md
[A Formal Commitment to New Language Features](http://jshint.com/blog/new-lang-features/ "A Formal Commitment to New Language Features")について
=> JSHint next

_i18n/ja/_posts/2015/2015-07-14-jquery.md, _i18n/ja/_posts/2015/2015-07-14-jquery3.0-jshint-esnext.md
=> 2015-07-14のJavaScript

.travis.yml, _i18n/ja/_posts/2014/2014-08-03-renewal.md, _i18n/ja/_posts/about/2015-06-10-about.md, _i18n/ko/_posts/2015/2015-06-23-es6-svg-jsconfus.md, _i18n/ko/_posts/about/2015-06-10-about.md, package.json, test/author-checker.js, test/category-checker.js, test/index-cheker.js, test/lib/MDFileParser.js, test/translator-checker.js
=> add category & author & translator check script

_i18n/ja/_posts/2015/2015-07-21-title.md, _i18n/ja/_posts/2015/2015-07-21-typescript1.5-webcomponents-browser.md
=> 2015-07-21のJavaScript

_i18n/ja/_posts/2015/2015-07-28-title.md
- [Chromium Blog: Chrome 45 Beta: New ES2015 features, service worker improvements, and media controls](http://blog.chromium.org/2015/07/chrome-45-beta-new-es2015-features.html)
- [ECMAScript 6 Features - ALPROSYS](http://www.alprosys.com/es6/es6_features_ol.html)
- [ECMAScript 6 Tutorial](http://ccoenraets.github.io/es6-tutorial/index.html)
- [Introduction | Down and Dirty with Chrome Developer Tools](http://blittle.github.io/chrome-dev-tools/)
=> 2015-07-28のJavaScript

.travis.yml
=> [WIP] レビューコメントLintを有効化

_i18n/ja/_posts/2015/2015-08-03-eslint-jscs-esprima.md, _i18n/ja/_posts/2015/2015-08-03-title.md
=> 2015-08-03のJavaScript

_i18n/ja/_posts/2015/2015-08-17-redux-flux-utils-firefox40.md, _i18n/ja/_posts/2015/2015-08-17-title.md
=> 2015-08-17のJavaScript

_i18n/ja/_posts/2015/2015-08-24-bootstrap-postcss-node-iojs.md, _i18n/ja/_posts/2015/2015-08-24-title.md
=> 2015-08-24のJavaScript

_i18n/ja/_posts/2015/2015-08-26-update-logo.md
- https://github.com/jser/jser.info/issues/4
=> JSer.infoのロゴやアイコンの更新について

_i18n/ja/_posts/2015/2015-09-02-msedge-unidirectional-architectures-read-css.md, _i18n/ja/_posts/2015/2015-09-02-title.md
- [Release version 10532 [PC] : Microsoft Edge Dev](http://dev.modern.ie/platform/changelog/10532-pc/)
- [André Staltz - Unidirectional User Interface Architectures](http://staltz.com/unidirectional-user-interface-architectures.html)
- [基本の前の基礎知識 - Back to Basics CSS 2015-08-30](http://unformedbuilding.com/slide/back-to-basics-2015-08-30/#/)
=> 2015-09-02のJavaScript

_i18n/ko/_posts/2015/2015-09-02-msedge-unidirectional-architectures-read-css.md
大変お久しぶりでございます。
ジョウンです。
２０１５年９月２日のJSを翻訳しました。
宜しくお願い申し上げます。
=> ２０１５年の９月のJSの韓国語の翻訳本

_i18n/ko/_posts/2015/2015-09-09-node4.0.0-typescript1.6beta-react.md
=> ２０１５年の９月９日のJSの韓国語の翻訳本

_i18n/ja/_posts/2015/2015-09-16-react-0.14-eslint-1.4-es5.md, _i18n/ja/_posts/2015/2015-09-16-title.md
- [React v0.14 Release Candidate | React](http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html)
- [ESLint v1.4.0 released - ESLint - Pluggable JavaScript linter](http://eslint.org/blog/2015/09/eslint-v1.4.0-released/)
- [ES2015(ES6)な時代だからこそ、ES5を改めて調べたJavaScript初級者のメモ - Qiita](http://qiita.com/zaru/items/d833dca52962c3f7770f)
=> 2015-09-16のJavaScript

_i18n/ko/_posts/2015/2015-09-16-react-0.14-eslint-1.4-es5.md
=> translate 09-16 @korean

_i18n/ja/_posts/2015/2015-09-25-firefox41-npm3-xregexp3.md, _i18n/ja/_posts/2015/2015-09-25-title.md
=> 2015-09-25のJavaScript

_i18n/ja/_posts/2015/2015-10-08-react0.14-eslint-tail-call.md
- [React v0.14 | React](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)
- [ESLint: The Next-Generation JavaScript Linter – Smashing Magazine](http://www.smashingmagazine.com/2015/09/eslint-the-next-generation-javascript-linter/)
- [JavaScript - 末尾再帰による最適化 - Qiita](http://qiita.com/pebblip/items/cf8d3230969b2f6b3132)
=> 2015-10-08のJavaScript

_i18n/ja/_posts/2015/2015-10-25-eslint-ecmascript-rollup.md
- [ESLint v1.7.0 released - ESLint - Pluggable JavaScript linter](http://eslint.org/blog/2015/10/eslint-v1.7.0-released/)
- [JavaScript - ESLint 最初の一歩 - Qiita](http://qiita.com/mysticatea/items/f523dab04a25f617c87d)
- [ECMAScriptの仕様策定に関するカンニングペーパー | Web Scratch](http://efcl.info/2015/10/18/ecmascript-paper/)
- [rollup.js](http://rollupjs.org/)
- [The struggles of publishing a JavaScript library | Read the Tea Leaves](http://nolanlawson.com/2015/10/19/the-struggles-of-publishing-a-javascript-library/)
=> 2015-10-25のJavaScript

_i18n/ja/_posts/2015/2015-11-09-large-refactoring-firefox44.md, _i18n/ja/_posts/2015/2015-11-09-title.md
=> 2015-11-09のJavaScript

_i18n/ja/_posts/2015/2015-11-16-ecmascript-7-ms-node-js.md, _i18n/ja/_posts/2015/2015-11-16-title.md
- [What’s in ECMAScript 2016 (ES7)?](http://www.2ality.com/2015/11/tc39-process.html)
- [ES6 in Practice](http://www.slideshare.net/teppeis/es6-in-practice)
- [Microsoft/nodejs-guidelines](https://github.com/Microsoft/nodejs-guidelines)
=> 2015-11-16のJavaScript

.babelrc, .textlintrc, .travis.yml, CONTRIBUTING.md, README.md, _i18n/ja/_posts/2015/2015-11-16-ecmascript-7-ms-node-js.md, circle.yml, package.json, test/travis-spellcheck.sh
close https://github.com/jser/jser.github.io/issues/186
=> Add Circle CI

_i18n/ja/_posts/2015/2015-11-23-jsdoc3.4.0-grunt-bower-js-trends.md, _i18n/ja/_posts/2015/2015-11-23-title.md
- Grunt / Bower?
- [Release JSDoc 3.4.0 · jsdoc3/jsdoc](https://github.com/jsdoc3/jsdoc/releases/tag/3.4.0 "Release JSDoc 3.4.0 · jsdoc3/jsdoc")
- トレンド
=>  2015-11-23のJavaScript

_layouts/default.html
Gitterを直接サイドバーに表示出来るように
https://sidecar.gitter.im/
=> feat(gitter): Add gitter sidecar

_i18n/ja/_posts/2015/2015-12-01-edgehtm13-typescrip1.7-prgressive.md, _i18n/ja/_posts/2015/2015-12-01-title.md
- [Announcing TypeScript 1.7 - TypeScript - Site Home - MSDN Blogs](http://blogs.msdn.com/b/typescript/archive/2015/11/30/announcing-typescript-1-7.aspx)
- [Introducing EdgeHTML 13, our first platform update for Microsoft Edge | Microsoft Edge Dev Blog](http://blogs.windows.com/msedgedev/2015/11/16/introducing-edgehtml-13-our-first-platform-update-for-microsoft-edge/)
- [Introducing Pokedex.org: a progressive webapp for Pokémon fans — Pocket JavaScript](http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org)
=> 2015-12-01のJavaScript

_i18n/ja/_posts/2015/2015-12-07-jasmine2.4-redux-firefox.md, _i18n/ja/_posts/2015/2015-12-07-title.md
https://monosnap.com/file/irp2XkqW8cuWDcQGxyotfqhvghviGE.png
https://github.com/azu/jasmine-random-example
htmlなら動く
=> 2015-12-07のJavaScript

_i18n/ko/_posts/2015/2015-11-03-vue1.0-babel6.0-node5.0.md
=> translate to korean 2015-11-03

_i18n/ja/_posts/2015/2015-12-22-angular2beta-ServiceWorker-css.md, _i18n/ja/_posts/2015/2015-12-22-title.md
- [総行数57,000の巨大CSS群をLessに書き換えた軌跡 - mixi Engineers' Blog](http://alpha.mixi.co.jp/entry/2015/12/20/000000)
- [WebCompat](http://wontfix.blogspot.jp/2015/08/webcompat.html)
- [Angular 2 Beta](http://angularjs.blogspot.jp/2015/12/angular-2-beta.html)
- [Beyond Offline ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2015/12/beyond-offline/)
=> 2015-12-22のJavaScript

_i18n/ja/_posts/2015/2015-12-30-corejs2.0.0-react-javascript-jargon.md, _i18n/ja/_posts/2015/2015-12-30-title.md
- [Release 2.0.0 - 2015.12.24 · zloirock/core-js](https://github.com/zloirock/core-js/releases/tag/v2.0.0)
- [React Developer Survey Results - AngularClass](https://angularclass.com/react-developer-survey-results/)
- [HugoGiraudel/SJSJ](https://github.com/HugoGiraudel/SJSJ)
- [Should I use React.createClass, ES6 Classes or stateless functional components? - James K Nelson](http://jamesknelson.com/should-i-use-react-createclass-es6-classes-or-stateless-functional-components/)
=> 2015-12-30のJavaScript

_i18n/ja/_posts/2016/2016-01-06-react-vender-prefix-babel-book.md
- [Webkit! RESOLVED FIXED - otsukare](http://www.otsukare.info/2016/01/04/webkit-resolved-fixed)
- [Well, I'm Back: innerText: Cleaning A Dark Corner Of the Web](http://robert.ocallahan.org/2016/01/innertext.html)
- [Setting up ES6 by Axel Rauschmayer [Leanpub PDF/iPad/Kindle]](https://leanpub.com/setting-up-es6)
- [petehunt/react-howto](https://github.com/petehunt/react-howto)
=> 2016-01-06のJavaScript

_i18n/ja/_posts/2016/2016-01-16-jser-5years.md
close https://github.com/jser/jser.info/issues/54
=> JSer.info 5周年

_i18n/ja/_posts/2016/2016-01-20-jquery3beta-esnext-news-chkracore.md
- [jQuery 3.0 Beta Released | Official jQuery Blog](http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/)
- [ChakraCore GitHub repository is now open | Microsoft Edge Dev Blog](https://blogs.windows.com/msedgedev/2016/01/13/chakracore-now-open/)
- [ES.next News: a weekly email newsletter](http://www.2ality.com/2016/01/esnext-news.html)
=> 2016-01-20のJavaScript

_i18n/ja/_posts/2016/2016-01-26-oop-fetch-stream-es6-cheatsheet.md, _i18n/ja/_posts/2016/2016-01-26-title.md
- [OO Relationships — Medium](https://medium.com/@DmitrySoshnikov/oo-relationships-5020163ab162#.s95wzdtib)
- [2016 - the year of web streams - JakeArchibald.com](https://jakearchibald.com/2016/streams-ftw/)
- [ECMAScript 2015 by David Leonard](http://slides.com/drksephy/ecmascript-2015#/)
- [DrkSephy/es6-cheatsheet](https://github.com/DrkSephy/es6-cheatsheet)
=> 2016-01-26のJavaScript

_i18n/ja/_posts/2016/2016-01-26-oop-fetch-stream-es6-cheatsheet.md
修正する必要性は小さいと思われますが、一応、他の項目の説明における表記に合わせるという形で修正しました。
=> fix a typo

_i18n/ja/_posts/2016/2016-02-02-firefox44-es2016-new-feature-webpack2beta.md
- [Firefox 44.0 リリースノート](https://www.mozilla.jp/firefox/44.0/releasenotes/)
- [ECMAScript 2016 features & changes - JSer.info](http://jser.info/2016/02/01/es2016/)
- [What's new in webpack 2](https://gist.github.com/sokra/27b24881210b56bbaff7)
=> 2016-02-02のJavaScript

_i18n/ja/_posts/2016/2016-02-08-babel6.5.0-angular1.5-let-const.md
- [Release v6.5.0 · babel/babel](https://github.com/babel/babel/releases/tag/v6.5.0)
- [Angular 1.5.0 - ennoblement-facilitation has been released!](http://angularjs.blogspot.jp/2016/02/angular-150-ennoblement-facilitation.html)
- [ES6 const is not about immutability · Mathias Bynens](https://mathiasbynens.be/notes/es6-const)
=> 2016-02-08のJavaScript

_i18n/ja/_posts/2016/2016-02-08-babel6.5.0-angular1.5-let-const.md
=> Fix typo "適当" => "適用"

_i18n/ja/_posts/2016/2016-02-15-grunt-eslint2.0.0-underscore-lodash.md
- [Grunt 1.0.0 rc1 released - Grunt: The JavaScript Task Runner](http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released)
- [ESLint v2.0.0 released - ESLint - Pluggable JavaScript linter](http://eslint.org/blog/2016/02/eslint-v2.0.0-released)
- [cht8687/You-Dont-Need-Lodash-Underscore: Lists of Javascript methods which you can use natively](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore)
- [stevemao/You-Dont-Know-About-Lodash-Underscore: In response to You-Dont-Need-Lodash-Underscore](https://github.com/stevemao/You-Dont-Know-About-Lodash-Underscore)
+ underdash
=> 2016-02-15のJavaScript

_i18n/ja/_posts/2016/2016-02-24-typescript1.8-react-semver-draft.md
- [Announcing TypeScript 1.8 | TypeScript](https://blogs.msdn.microsoft.com/typescript/2016/02/22/announcing-typescript-1-8-2/)
- [New Versioning Scheme | React](http://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html)
- [Draft.js | Rich Text Editor Framework for React](https://facebook.github.io/draft-js/)
=> 2016-02-24のJavaScript

_i18n/ja/_posts/2016/2016-03-03-ember-lts-402-i18n-rc-jquery3.md
- [Ember.js - Announcing Ember's First LTS Release](http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html)
- [tc39/ecma402: Status, process, and documents for ECMA 402](https://github.com/tc39/ecma402)
- [Exposing `CanonicalizeLocaleList()` abstract operation via `Intl.getCanonicalLocales()` by caridy · Pull Request #78 · tc39/ecma402](https://github.com/tc39/ecma402/pull/78)
- [What's New in jQuery 3 - Telerik Developer Network](http://developer.telerik.com/featured/whats-new-in-jquery-3/)
=> 2016-03-03 JavaScript

_i18n/ja/_posts/2016/2016-03-08-react15.0rc-perf-ddd.md
- [JavaScript+DDD実践編？ // Speaker Deck](https://speakerdeck.com/yaakaito/javascript-plus-dddshi-jian-bian)
- [大型フロントエンド開発におけるTypeScriptとDDD // Speaker Deck](https://speakerdeck.com/armorik83/da-xing-hurontoendokai-fa-niokerutypescripttoddd)
- [フロントエンドはDDDの夢を見るか // Speaker Deck](https://speakerdeck.com/yukieen/hurontoendohadddfalsemeng-wojian-ruka)
- [React v15.0 Release Candidate | React](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html)
=> 2016-03-08のJavaScript

_i18n/ja/_posts/2016/2016-03-17-react-webassembly-art-of-javascript.md
- [React v15.0 Release Candidate 2 | React](https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html)
- [A WebAssembly Milestone: Experimental Support in Multiple Browsers ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/03/a-webassembly-milestone/)
- [WebAssembly](http://webassembly.github.io/)
- [State of the Art JavaScript in 2016 — JavaScript and Opinions — Medium](https://medium.com/javascript-and-opinions/state-of-the-art-javascript-in-2016-ab67fc68eb0b#.wb79y46uj)
=> 2016-03-17のJavaScript

_i18n/ja/_posts/2016/2016-03-23-chrom50beta-react-perf-node-compat-table.md
- [Developer Edition 47 – User agent emulation, popup debugging and more ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/03/developer-edition-47-user-agent-emulation-popup-debugging-and-more/)
- [Animating with React, Redux, and d3 | A geek with a hat](http://swizec.com/blog/animating-with-react-redux-and-d3/swizec/6775)
- [Reactを使ったプロダクトのパフォーマンスを改善した話 | GMOメディア エンジニアブログ](http://tech.gmo-media.jp/post/141458071484/react-perf-tuning)
- [Node.js ES2015/ES6 support](http://node.green/)
- [Chromium Blog: Chrome 50 Beta: Push notification improvements and declarative preload](http://blog.chromium.org/2016/03/chrome-50-beta-push-notification.html)
=> 2016-03-23のJavaScript

_i18n/ja/_posts/2016/2016-03-29-safari-91backbonejsweb-performance-api.md
Backbone
- [Backbone.js](http://backbonejs.org/)
- [The Sad State of the Backbone Ecosystem](http://benmccormick.org/2016/03/07/the-sad-state-of-the-backbone-ecosystem/)
Perf
- [Proposal: Sandbox Policy - HTML - WICG](https://discourse.wicg.io/t/proposal-sandbox-policy/1414)
- [A Primer for Web Performance Timing APIs](https://w3c.github.io/perf-timing-primer/)
- [ブラウザのPerformance APIの話](http://www.slideshare.net/kawada_hiroshi/performance-api)
CPP
Safari
- [Safari 9.1](https://developer.apple.com/library/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html)
- [CSS Variables in WebKit | WebKit](https://webkit.org/blog/5989/css-variables-in-webkit/)
- [Safari on iOS 9.3, Responsive Images, iPhone SE, shrink-to-fit and other new APIs | Breaking the Mobile …
=> 2016-03-29のJavaScript

_i18n/ja/_posts/2016/2016-04-04-nodejs-5100npm-security-fixsafari-technology-preview.md, _i18n/ja/_posts/2016/2016-04-04-title.md
- [Node v5.10.0 (Stable) | Node.js](https://nodejs.org/en/blog/release/v5.10.0/)
- [The npm Blog — fixing a bearer token vulnerability](http://blog.npmjs.org/post/142036323955/fixing-a-bearer-token-vulnerability)
- [ECSS: Home Page](http://ecss.io/)
- [Introducing Safari Technology Preview | WebKit](https://webkit.org/blog/6017/introducing-safari-technology-preview/)
=> 2016-04-04のJavaScript

_i18n/ja/_posts/2016/2016-04-11-grunt-100react-150javascript.md, _i18n/ja/_posts/2016/2016-04-11-title.md
- [React v15.0 | React](https://facebook.github.io/react/blog/2016/04/07/react-v15.html)
- [Grunt 1.0.0 released - Grunt: The JavaScript Task Runner](http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released)
- [Tools to Learn JavaScript By Doing -Telerik Developer Network](http://developer.telerik.com/featured/tools-learn-javascript/ "Tools to Learn JavaScript By Doing -Telerik Developer Network")
=> 2016-04-11のJavaScript

_i18n/ja/_posts/2016/2016-04-18-jscs-30eslintsvg.md
- [JSCS, CST и новое начало / Хабрахабр](https://habrahabr.ru/post/281635/)
- [Issues · eslint/eslint](https://github.com/eslint/eslint/milestones/JSCS%20Compatibility)
- [JSCS — end of the line — Medium](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2)
- [Mike Sherov on Twitter: "@tbranyen @arkel @jquery @geteslint @jscs_dev you can still use JSCS, and you can use ESLint with only style rules if you like."](https://twitter.com/mikesherov/status/720697270019170304)
- [Scalable Single-Page Application Architecture – Minko Gechev's blog](http://blog.mgechev.com/2016/04/10/scalable-javascript-single-page-app-angular2-application-architecture/)
- [How to work with SVG icons](http://fvsch.com/code/svg-icons/how-to/)
=> 2016-04-18のJavaScript

_i18n/ja/_posts/2016/2016-04-26-core-js-230addeventlistener3.md
- [Release 2.3.0 - 2016.04.24 · zloirock/core-js](https://github.com/zloirock/core-js/releases/tag/v2.3.0)
- [emilbjorklund/svg-weirdness: A repository of bugs and plain weird behavior in SVG](https://github.com/emilbjorklund/svg-weirdness)
- [ウェブ関連仕様 日本語訳](https://triple-underscore.github.io/)
- [Lint your CSS with stylelint | CSS-Tricks](https://css-tricks.com/stylelint/)
- [DOM Listener: capture, passive, and once](https://www.webreflection.co.uk/blog/2016/04/17/new-dom4-standards)
- [html · momdo/momdo.github.io Wiki](https://github.com/momdo/momdo.github.io/wiki/html)
=> 2016-04-26のJavaScript

_i18n/ja/_posts/2016/2016-05-03-nodejs-600github-fetch-100-webkit-prefix.md
- [Node v6.0.0 (Current) | Node.js](https://nodejs.org/en/blog/release/v6.0.0/)
- [Release Fetch 1.0.0 · github/fetch](https://github.com/github/fetch/releases/tag/v1.0.0)
- [Updating Our Prefixing Policy | WebKit](https://webkit.org/blog/6131/updating-our-prefixing-policy/)
=> 2016-05-03のJavaScript

_i18n/ja/_posts/2016/2016-05-16-electron-10buble.md
- [Electron 1.0](http://electron.atom.io/blog/2016/05/11/electron-1-0)
- [ブレークポイントを使ったJavaScriptデバッグを整理してみた【再入門】 - Qiita](http://qiita.com/nekoneko-wanwan/items/02aed17773833c3ad3b2)
- [Bublé – the blazing fast, batteries-included ES2015 compiler](https://buble.surge.sh/guide/)
=> 2016-05-16のJavaScript

_i18n/ja/_posts/2016/2016-05-30-npm-publishnodejs.md, _i18n/ja/_posts/2016/2016-05-30-title.md
- [Publishing Your First Package to npm](https://eladnava.com/publishing-your-first-package-to-npm/)
- [Fullstack React 🐬: React Tutorial: Cloning Yelp](https://www.fullstackreact.com/articles/react-tutorial-cloning-yelp/)
- [React/Redux Introduction // Speaker Deck](https://speakerdeck.com/adwd/redux-introduction)
何か足りない感じがする
=> 2016-05-30のJavaScript

_i18n/ja/_posts/2016/2016-06-07-shadow-dom-v1reactjavascript.md
- [What's New in Shadow DOM v1 (by examples) — hayato.io](http://hayato.io/2016/shadowdomv1/)
- [webpackのDLLバンドルを使ってビルドを速くする - Qiita](http://qiita.com/pirosikick/items/c77db84dbed4c447a6fe)
- [gaearon/todos: Examples for “Idiomatic Redux”: one branch per lesson](https://github.com/gaearon/todos)
- [JavaScript Plugin Architectureというプラグイン設計について学ぶ無料の電子書籍を書いた | Web Scratch](http://efcl.info/2016/06/06/JavaScript-Plugin-Architecture/)
- [Hayato (Shadow DOM) (@shadow_hayato) | Twitter](https://twitter.com/shadow_hayato)
- [Shadow DOM v1: Status updates - Google グループ](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/BUGxw_Yx5Lo)
- [Issue 1995203002: Rewrite Shadow DOM distribution engine to support partial synchronous distribution for v1 - Code …
=> 2016-06-07のJavaScript

_i18n/ko/_posts/2016/2016-06-07-shadow-dom-v1reactjavascript.md
=> translate to korean 2016-06-07

_i18n/ja/_posts/2016/2016-06-13-jQuery3-Firefox47-WebAudioAPI.md
- [jQuery 3.0 Final Released! | Official jQuery Blog](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/)
- [Firefox 47.0 リリースノート](https://www.mozilla.jp/firefox/47.0/releasenotes/)
- [web audio lesson](http://mohayonao.github.io/web-audio-lesson/#lesson05)
- [CSS containment | justmarkup](https://justmarkup.com/log/2016/04/css-containment/)
- [web-audio-lesson : Web Audio API初学者向けのテキストを書きました - 音の鳴るブログ](http://mohayonao.hatenablog.com/entry/2016/06/12/154735)
=> 2016-06-13のJavaScript

_i18n/ja/_posts/2016/2016-07-11-jquery-31nodejs-63web-animations-api.md, _i18n/ja/_posts/2016/2016-07-11-title.md
- [jQuery 3.1.0 Released – No More Silent Errors | Official jQuery Blog](http://blog.jquery.com/2016/07/07/jquery-3-1-0-released-no-more-silent-errors/)
- [Node v6.3.0 (Current) | Node.js](https://nodejs.org/en/blog/release/v6.3.0/)
- [Web Animations APIの基本的な使い方・まとめ](http://www.h2.dion.ne.jp/%7Edefghi/webanim/webanim.htm)
=> 2016-07-11 JavaScript

_i18n/ja/_posts/2016/2016-07-19-async-20axe-20typescript-20b.md
- [async/CHANGELOG.md at v2.0.0 · caolan/async](https://github.com/caolan/async/blob/v2.0.0/CHANGELOG.md)
- [Announcing TypeScript 2.0 Beta | TypeScript](https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/)
- [Deque Launches aXe 2.0](http://www.deque.com/blog/introducing-axe-2-0/)
=> 2016-07-19 JavaScript

_i18n/ja/_posts/2016/2016-08-01-mocha-30react-1530ecmascript-proposal.md
- [mocha/CHANGELOG.md at master · mochajs/mocha](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md)
- [ECMAScript proposal updates @ 2016-07 | ECMAScript Daily](https://ecmascript-daily.github.io/2016/07/30/last-minutes-proposals-changes)
- [Release v15.3.0 · facebook/react](https://github.com/facebook/react/releases/tag/v15.3.0)
=> 2016-08-01 JavaScript

_i18n/ja/_posts/2016/2016-08-09-firefox-480nodewhatwg-streamwebpack.md
- [Firefox — Notes (48.0) — Mozilla](https://www.mozilla.org/en-US/firefox/48.0/releasenotes/)
- [Animating like you just don’t care with Element.animate ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/08/animating-like-you-just-dont-care-with-element-animate/)
- [stream between nodejs and whatwg // Speaker Deck](https://speakerdeck.com/jxck/stream-between-nodejs-and-whatwg)
- [step by stepで始めるwebpack - Qiita](http://qiita.com/howdy39/items/48d85c430f90a21075cd)
=> 2016-08-09のJavaScript

_i18n/ja/_posts/2016/2016-08-15-chrome-53-beta60fps-css-animation.md
- [Chromium Blog: Chrome 53 Beta: Shadow DOM, PaymentRequest, and Android autoplay](http://blog.chromium.org/2016/08/chrome-53-beta-shadow-dom.html)
- [Make your JavaScript code shine: knockout old ES5 hacks](https://rainsoft.io/make-your-javascript-code-shide-knockout-old-es5-hack/)
- [Smooth as Butter: Achieving 60 FPS Animations with CSS3 — OutSystems Experts — Medium](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108#.boi1iv46j)
=> 2016-08-15のJavaScript

_i18n/ja/_posts/2016/2016-08-23-web-audio-apiangularjs-2-rc5ngmoduleproperty-based-testing.md
- [What’s new in Web Audio? ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/08/whats-new-in-web-audio-2/)
- [What’s new in Web Audio? | Mozilla Developer Street (modest)](https://dev.mozilla.jp/2016/08/whats-new-in-web-audio-2/)
- [Angular2 RC5への更新とステート管理の変更、power-assertによるテストまで試す - undefined](http://blog.bokuweb.me/entry/angular2_rc5)
- [Generative Testing in JavaScript — JavaScript Inside — Medium](https://medium.com/javascript-inside/generative-testing-in-javascript-f91432247c27#.438hlwrg6)
=> 2016-08-23のJavaScript

_i18n/ja/_posts/2016/2016-08-30-pixijs-babel-jsframwork.md
- [Release v4.0.0 · pixijs/pixi.js](https://github.com/pixijs/pixi.js/releases/tag/v4.0.0)
- [Issues · pixijs/pixi.js](https://github.com/pixijs/pixi.js/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.1)
- [Release v6.14.0 · babel/babel](https://github.com/babel/babel/releases/tag/v6.14.0)
- [The State Of JavaScript: Front-End Frameworks – Medium](https://medium.com/@sachagreif/the-state-of-javascript-front-end-frameworks-1a2d8a61510#.n7d3a66cu)
- [The State Of JavaScript](http://stateofjs.com/)
=> 2016-08-30のJavaScript

_i18n/ja/_posts/2016/2016-09-05-babili-atypescript20-rcsass-35-rc.md, _i18n/ja/_posts/2016/2016-09-05-title.md
- [Announcing TypeScript 2.0 RC | TypeScript](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/)
- [Babili (babel-minify) · Babel](https://babeljs.io/blog/2016/08/30/babili)
- [Sass 3.5 Release Candidate « Sass Blog](http://blog.sass-lang.com/posts/809572-sass-35-release-candidate)
=> 2016-09-05 JavaScript

_i18n/ja/_posts/2016/2016-09-12-polymer-20aservice-workerjs.md
- [Polymer 2.0 Preview - Polymer Project](https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0)
- [Release v0.32.0 · facebook/flow](https://github.com/facebook/flow/releases/tag/v0.32.0)
- [Service Workerの基本とそれを使ってできること - Qiita](http://qiita.com/y_fujieda/items/f9e765ac9d89ba241154)
- [Service Worker の紹介 | Web Fundamentals - Google Developers](https://developers.google.com/web/fundamentals/primers/service-worker/)
- [flowtype v0.32.0 changes - Please Drive Faster](http://joe-re.hatenablog.com/entry/2016/09/06/101529)
- [Microsoft/dts-gen: dts-gen creates starter TypeScript definition files for any module or library.](https://github.com/Microsoft/dts-gen)
=> 2016-09-12のJavaScript

_i18n/ja/_posts/2016/2016-09-20-angularjs-2node-660chrome.md
- [Angular, version 2: proprioception-reinforcement](http://angularjs.blogspot.jp/2016/09/angular2-final.html)
- [🎉✨ Angular 2.0.0がリリースされました 🎉✨ · Angular2 Info](https://ng2-info.github.io/2016/09/angular-2-final/)
- [Node v6.6.0 (Current) | Node.js](https://nodejs.org/en/blog/release/v6.6.0/)
=> 2016-09-20のJavaScript

_config.yml, _includes/ogp.html, _includes/sidebar.html, _includes/social-boorkmark.html, _layouts/post.html, public/event/textillate/index.html, src/related-item.js
=> chore: http => https

_i18n/ja/_posts/2016/2016-10-10-javascriptunicodeweb-componentsnpm-scripts.md
300回目 :pushpin:
- [What every JavaScript developer should know about Unicode](https://rainsoft.io/what-every-javascript-developer-should-know-about-unicode/)
- [Web Components 2016 & Polymer v2](https://1000ch.github.io/slide/webcomponents-2016/#)
- [npm-scripts で Web フロントエンド開発を管理する – アカベコマイリ](http://akabeko.me/blog/2016/10/npm-scripts-web-front-end-development/)
- [scripts | npm Documentation](https://docs.npmjs.com/misc/scripts)
=> 2016-10-10のJavaScript 📌

_i18n/ja/_posts/2016/2016-10-18-js-foundation-npmyarn.md, _i18n/ja/_posts/2016/2016-10-18-title.md
- [The Linux Foundation Unites JavaScript Community for Open Web Development | The JS Foundation](https://js.foundation/announcements/2016/10/17/Linux-Foundation-Unites-JavaScript-Community-Open-Web-Development/)
- [Yarn](https://yarnpkg.com/)
- [Yarn: A new package manager for JavaScript | Engineering Blog | Facebook Code](https://code.facebook.com/posts/1840075619545360)
- [Migrating from npm | Yarn](https://yarnpkg.com/en/docs/migrating-from-npm)
=> 2016-10-18のJavaScript

_i18n/ja/_posts/2016/2016-10-18-js-foundation-npmyarn.md
=> Avoid email protection

_i18n/ja/_posts/2016/2016-11-08-sitespeed.io-4.0-webpack-2-beta-javascript.md
- [Welcome sitespeed.io 4.0](https://www.sitespeed.io/sitespeed.io-4.0-is-released/)
- [sitespeed.io 4.0 · Issue #813 · sitespeedio/sitespeed.io](https://github.com/sitespeedio/sitespeed.io/issues/813 "sitespeed.io 4.0 · Issue #813 · sitespeedio/sitespeed.io")
- [Getting Started with Webpack 2](https://blog.madewithenvy.com/getting-started-with-webpack-2-ed2b86c68783#.2396djdk8)
- [what is the timeline for the release of webpack 2? · Issue #1545 · webpack/webpack](https://github.com/webpack/webpack/issues/1545#issuecomment-255614222 "what is the timeline for the release of webpack 2? · Issue #1545 · webpack/webpack")
- [takahashim/js-stack-from-scratch: Step-by-step tutorial to build a modern JavaScript stack from scratch](https://github.com/takahashim/js-stack-from-scratch)
=> 2016-11-08のJavaScript

_i18n/ja/_posts/2016/2016-11-22-firefox-50-react-v15.4.0-custom-element-v1.md
- [Firefox 50.0 リリースノート](https://www.mozilla.jp/firefox/50.0/releasenotes/)
- [Firefox 50 for developers - Mozilla | MDN](https://developer.mozilla.org/ja/Firefox/Releases/50)
- [Firefox 50 サイト互換性情報 | Firefox サイト互換性情報](https://www.fxsitecompat.com/ja/versions/50/)
- [performance.markでパフォーマンス計測する | Web Scratch](http://efcl.info/2016/08/15/performance.mark/)
- [React v15.4.0 - React Blog](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html)
- [`injectEnvironment` called twice: `react-test-renderer` and `react-dom` · Issue #7386 · facebook/react](https://github.com/facebook/react/issues/7386)
- [Introducing Custom Elements | WebKit](https://webkit.org/blog/7027/introducing-custom-elements/)
=> 2016-11-22のJavaScript

_i18n/ja/_posts/2016/2016-12-06-ember.js-2.10-front-end-tooling-2016-svelte.md, _i18n/ja/_posts/2016/2016-12-06-title.md
- [Ember.js - Ember 2.10 and 2.11 Beta Released](http://emberjs.com/blog/2016/11/30/ember-2-10-released.html)
- [Ember.js - Announcing The Glimmer 2 Alpha](http://emberjs.com/blog/2016/07/29/announcing-the-glimmer-2-alpha.html)
- [The State of Front-End Tooling 2016 - Results - AshleyNolan.co.uk - Blog and Portfolio for Ashley Nolan](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2016-results)
- [Frameworks without the framework: why didn't we think of this sooner? • Svelte](https://svelte.technology/blog/frameworks-without-the-framework/)
- [Svelte • The magical disappearing UI framework](https://svelte.technology/)
- [Frameworks without the framework: why didn't we think of this sooner? • Svelte](https://svelte.technology/blog/frameworks-without-the-framework/)
=> 2016-12-06のJavaScript

_i18n/ja/_posts/2016/2016-12-20-rxjs-v5-angular-date-fns.md
- [ReactiveX/rxjs: A reactive programming library for JavaScript](https://github.com/ReactiveX/rxjs)
- [Reactive-Extensions/RxJS: The Reactive Extensions for JavaScript](https://github.com/Reactive-Extensions/RxJS)
- [Angular: Angular 1.6.0 released](http://angularjs.blogspot.jp/2016/12/angular-160-released.html)
- [Angular: Ok... let me explain: it's going to be Angular 4.0, or just Angular](http://angularjs.blogspot.jp/2016/12/ok-let-me-explain-its-going-to-be.html)
- [date-fns/date-fns: ⏳ Modern JavaScript date utility library ⌛️](https://github.com/date-fns/date-fns)
=> 2016-12-20のJavaScript

_i18n/ja/_posts/2017/2017-01-04-postcss-chrome-fusebox.md
- [PostCSS まとめ - Qiita](http://qiita.com/morishitter/items/4a04eb144abf49f41d7d)
- [Optimise your web development workflow 2016](https://umaar.github.io/devtools-optimise-your-web-development-workflow-2016/#/)
- [Fuse-Box bundler / API Reference](http://fuse-box.org/)
- [fuse-box/fuse-box: A blazing fast js bundler/loader with a comprehensive API](https://github.com/fuse-box/fuse-box)
=> 2017-01-04のJavaScript

_i18n/ja/_posts/2017/2017-01-17-safari-technology-preview-release-21-protractor-5.0.0.md
- [Native ECMAScript modules - the first overview](https://blog.hospodarets.com/native-ecmascript-modules-the-first-overview)
- [protractor/CHANGELOG.md at 5.0.0 · angular/protractor](https://github.com/angular/protractor/blob/5.0.0/CHANGELOG.md)
- [Release Notes for Safari Technology Preview 21 | WebKit](https://webkit.org/blog/7265/release-notes-for-safari-technology-preview-21/)
- [Side Effects in JS Promise chains – Medium](https://medium.com/@gabrielcatalin/side-effects-in-js-promise-chains-7db50b6302f3#.f8zn8wyal)
=> 2017-01-17のJavaScript

_i18n/ja/_posts/2017/2017-01-24-title.md, _i18n/ja/_posts/2017/2017-01-24-webpack-2-javascript-2016-js-star.md
- [Release v2.2.0 · webpack/webpack](https://github.com/webpack/webpack/releases/tag/v2.2.0)
- [Migrating from v1 to v2](https://webpack.js.org/guides/migrating/)
- [🎉 webpack 2.2: The Final Release 🎉 – webpack – Medium](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144)
- [Modern JavaScript概観、そしてElectronへ](http://blog.satotaichi.info/modern-javascript_201701/)
=> 2017-01-24のJavaScript

.gitignore, .travis.yml, _i18n/ja/_posts/2017/2017-02-05-ava-0.18.0-mithril-1.0-es-moduleswebpack.md, circle.yml, package.json
Use [haya14busa/reviewdog: A code review dog who keeps your codebase healthy](https://github.com/haya14busa/reviewdog "haya14busa/reviewdog: A code review dog who keeps your codebase healthy")
=> Add reviewdog

_i18n/ja/_posts/2017/2017-08-08-storybook-3.2-core-js-2.5.0-flow-lint.md
ハイフンの前に ^H が入っていて valid な rss が生成されていなかった
=> Remove invalid character

_i18n/ja/_posts/2019/2019-09-30-455draft.md
「アップデートサれて」はおそらく「アップデートされて」の typo
=> fix minor typo "サれて" → "されて"

_i18n/ja/_posts/2019/2019-10-15-webpack-5bnext.jscreate-next-appsame-site-cookies.md
=> fix minor typo "サれた" → "された"

_i18n/ja/_posts/2019/2019-12-10-firefox-71.0webassembly-w3c-recommendationnullish-coalescing-and-optional-chaininges2020.md
https://developers.google.com/web/updates/2019/12/devtools#redeclarations
=> Support for let and class redeclarations in the Console

_i18n/ja/_posts/2020/2020-01-07-mocha-v7.0.0next.js-9.1.7typescript.md
https://github.com/mochajs/mocha/releases/tag/v7.0.0
=> Fix description of mocha v7

_i18n/ja/_posts/2020/2020-01-21-microsoft-edgechromium-basedava-3.0.md
「Cookie 概説 - 30歳からのプログラミング」を書籍関係から記事へアーティクルへ移動
=> 書籍関係から記事へアーティクルへ移動

_i18n/ja/_posts/2020/2020-07-28-sveltetypescript-chrome-85-beta-web-speed-hackathon-online.md
=> content-visibility

_i18n/ja/_posts/2020/2020-07-28-sveltetypescript-chrome-85-beta-web-speed-hackathon-online.md
=> typo in svelte section

_i18n/ko/_posts/2020/2020-08-11-react-17.0-rc-rome-thinking-in-microfrontend.md
=> Translate to korean 2020-08-11

_layouts/default.html
=> fix(html): add lang to html

_i18n/ja/_posts/2020/2020-10-27-react-17-node-v15.0.0-libsass-is-deprecated.md
https://github.com/facebook/create-react-app/releases/tag/v4.0.0
=> CRA updates ESLint 6 -> 7

_i18n/ja/_posts/2021/2021-04-06-typescript-4.3-beta-hls.js-v1.0.0apple-low-latency-hls-storybook-6.2.md
ref: https://jser.info/2021/04/06/typescript-4.3-beta-hls.js-v1.0.0apple-low-latency-hls-storybook-6.2/
=> Fix typo(tslint -> tslib)

_i18n/ja/_posts/2015/2015-12-30-corejs2.0.0-react-javascript-jargon.md
=> Update name references

_i18n/ja/_posts/2021/2021-11-23-typescript-4.5-react-18-beta-remix-v1.md
多分、これで意味が通ると思います。
あと、原文だとpurgeとかPurgeCSSという用語だったので、PruneをPurgeに置き換えました。
https://antfu.me/posts/reimagine-atomic-css
=> fix typo: Tailwind, Windi CSS

_i18n/ja/_posts/2022/2022-01-11-core-web-vitals-2021-javascript-rising-stars-colors.js.md
=> fix typo: 2022-01-11

_i18n/ja/_posts/2022/2022-01-16-11-years.md
11周年の記事
- 2025年までの目標: JSer.info を交換可能に
- [JSer.info 11周年アンケート](https://docs.google.com/forms/d/e/1FAIpQLSf-yM__dw6KMpNOteqGD1TfImG_Niv3c5XnYvpd1gT4qnZE5g/viewform): ぜひ答えてね
=> JSer.info 11周年

_i18n/ja/_posts/2022/2022-03-15-react-18-rc-playwright-v1.20.0-safari-15.4.md
たぶん `useId` が正しそう...？
https://github.com/reactwg/react-18/discussions/111
=> userId を useId に修正

_i18n/ko/_posts/2022/2022-04-06-react-18-vite-2.9.0-firefox.md
こんにちは、2022-04-06 ポストの韓国語翻訳本です。
=> Translate to Korean 2022-04-06 

_i18n/ko/_posts/2022/2022-04-18-lexical-react-testing-library-v13.1.0-dialog-component.md
こんにちは、2022-04-18　ポストの韓国語翻訳本です。
=> Translate to Korean 2022-04-18

_i18n/ko/_posts/2022/2022-05-17-solid-v1.4.0-playwright-v1.22.0-safari-15.5.md
=> Translate to Korean 2022-05-17

_i18n/ja/_posts/2022/2022-09-21-redwood-3.0.0-npm-wasmtime-1.0.md
=> fix: 送り仮名の追加

_i18n/ja/_posts/2022/2022-11-17-parcel-v2.8.0-deno-1.28npm-gatsby-5-nuxt-3.md, _i18n/ko/_posts/2022/2022-11-09-safari-technology-preview-157-hapi-v21.0.0-rome-v10stable.md, _i18n/ko/_posts/2022/2022-11-17-parcel-v2.8.0-deno-1.28npm-gatsby-5-nuxt-3.md
1. 2022-11-09 translate korean > 2022-11-09 韓国語翻訳しました。
2. modified miss typing > 2022-11-17のincrementlをincrementalに変更しました。
3. modified: choice a better word for アーティクル (기사 => 읽을거리) >  もっと読みやすい単語に変更しました。
4. 2022-11-17 translate korean > 2022-11-17 韓国語翻訳しました。
=> 20221109, 20221117 韓国語翻訳

_i18n/ja/_posts/2022/2022-11-17-parcel-v2.8.0-deno-1.28npm-gatsby-5-nuxt-3.md, _i18n/ko/_posts/2022/2022-11-09-safari-technology-preview-157-hapi-v21.0.0-rome-v10stable.md, _i18n/ko/_posts/2022/2022-11-17-parcel-v2.8.0-deno-1.28npm-gatsby-5-nuxt-3.md
=> 20221109, 20221117 title translate

_i18n/ko/_posts/2022/2022-11-22-state-of-javascript-2022-regexp-v-flag.md
=> ADD: translate korean 2022-11-22

_i18n/ja/_posts/2022/2022-11-29-esmeta-wasmer-3.0-trpc-v10.md, _i18n/ko/_posts/2022/2022-11-29-esmeta-wasmer-3.0-trpc-v10.md
=> 2022-11-29 翻訳

_i18n/ko/_posts/2022/2022-11-29-esmeta-wasmer-3.0-trpc-v10.md
=> 20221129 title translate

_i18n/ko/_posts/2022/2022-12-07-electron-22.0.0-web-performancejavascript-performance.md
=> 2022-12-07 翻訳しました

_i18n/ko/_posts/2022/2022-12-20-vite-4.0-sveltekit-1.0-node-v19.3.0npm-9-rum-archive.md
=> ADD: 20221220 korean translate

_i18n/ko/_posts/2022/2022-12-20-vite-4.0-sveltekit-1.0-node-v19.3.0npm-9-rum-archive.md, _i18n/ko/_posts/2022/2022-12-28-next.js-13.1-http3-prioritization-deno-1.29-bun-0.4.md
=> add: 20221228 translate korean

_i18n/ko/_posts/2023/2023-01-06-vue-2eol2023-nextauthauth.js-react-nativefirst-class-support-for-typescript.md
20230106を翻訳しました。
あけましておめでとうございます :)
=> 20230106 korean translate

_i18n/ko/_posts/2023/2023-02-08-node.js-v18.14.0npm-9.x-interop-2023-learn-images.md
=> ADD: translate 20230208

_i18n/ko/_posts/2023/2023-02-15-lighthouse-10-core-js-webcontainers.md
=> translate: 20232015 article

_i18n/ko/_posts/sponsor/2023-02-20-sponsor.md
=> Move to /ko/sponsor

_i18n/ko/_posts/2023/2023-03-08-jest-29.5.0-chrome-111-testing-library.md
=> translate: 20230308

_i18n/ko/_posts/2023/2023-03-14-storybook-7.0.0-rc-rspackwebpack-interoperability-pino-logging-guide.md
=> translate: 20230314

_i18n/ko/_posts/2023/2023-03-22-firefox-111-react.dev-typescript-5.md
=> translate: 20230322kr

_i18n/ko/_posts/2023/2023-03-29-safari-16.4-denocloudflare-workersnode.js-pnpm-8.0.0.md
=> translate: 20230329

_i18n/ko/_posts/2023/2023-04-07-rome-v12-es2023-rc-typescript-5.md
=> translate: 20230407

_i18n/ko/_posts/2023/2023-04-13-storybook-7.0-jspm-cli-next.js-13.3.md
=> translate: 20230413 | fix: miss type

_i18n/ko/_posts/2023/2023-04-19-vueuse-10.0.0-immer-10.0.0-node.js-20.0.0.md
=>  translate: 20230419 | fix: miss type

_i18n/ko/_posts/2023/2023-05-04-qwik-1.0.0-angular-16-karma.md
=> translate: 20230504

_i18n/ja/_posts/2023/2023-05-26-wrangler-v3.0.0-playwright-v1.34.0-typescript-5.2.md
Fix typo `worked` to `workerd`
=> Fix: fix typo of workerd

_i18n/ko/_posts/2023/2023-05-26-wrangler-v3.0.0-playwright-v1.34.0-typescript-5.2.md
=> translate: 2023-05-26 article

_i18n/ko/_posts/2023/2023-06-01-parcel-v2.9.0-deno-1.34-state-of-node.js-performance-2023.md
=> translate: 20230601 article

_i18n/ja/_posts/2023/2023-06-11-rspack-0.2-modern-css-polywasm.md, _i18n/ko/_posts/2023/2023-06-11-rspack-0.2-modern-css-polywasm.md
=> translate: 20230611 article

_i18n/ko/_posts/2023/2023-06-21-react-redux-v8.1.0-fresh-1.2-modern-css.md
=> translate: 20230621 article

_i18n/ko/_posts/2023/2023-06-29-svelte-4-ember-5.0-the-cost-of-javascript-in-2023.md
=> translate: 20230629 article

_i18n/ko/_posts/2023/2023-07-20-vm2-storybook-7.1-fresh-1.3.md
=> translate: 20230720 article

_i18n/ja/_posts/2023/2023-08-03-riot.js-v9.0.0-firefox-116-react-server-components.md
=> Fix broken link

_i18n/ko/_posts/2023/2023-08-03-riot.js-v9.0.0-firefox-116-react-server-components.md
=> translate: 20230803 article

_i18n/ko/_posts/2023/2023-08-10-lighthouse-v11.0.0-astro-2.10view-transitions-sharpwebassembly.md
=> translate: 20230810 article

_i18n/ko/_posts/2023/2023-08-16-next.js-v13.4.16test-mode-safaristorage-policy-esmredux.md
=> translate: 20230816 article

_i18n/ko/_posts/2023/2023-08-24-fresh-1.4-chrome-117-beta-bun-0.8.0.md
=> translate: 20230824

_i18n/ko/_posts/2023/2023-09-07-node.js-v20.6.0.env-rspack.md
=> translate: 20230907 article

_i18n/ko/_posts/2023/2023-09-15-bun-v1.0-node.js-16eol-state-of-css-2023.md
=> translate: 20230915 article

_i18n/ko/_posts/2023/2023-09-22-remix-v2-safari-17-typescript.md
=> translate: 20230922 article

_i18n/ko/_posts/2023/2023-09-29-babel-v7.23.0-vike-state-of-html-2023.md
=> translate: 20230929 article

_i18n/ko/_posts/2023/2023-10-10-rollup-4.0.0-viterustify-vite-pnpm-v8.9.0.md
=> translate: 20231010 article

_i18n/ko/_posts/2023/2023-10-31-next.js-14-msw-2-node.js-21.1.0.md
=> translate: 20231031

_i18n/ko/_posts/2023/2023-11-08-remix-2.2.0vite-deno-1.38-angular.dev.md
=> translate: 20231108 article

_i18n/ko/_posts/2023/2023-11-16-angular-v17-prettier-3.1-node.js-v21.2.0.md
=> translate: 20231116 article

_i18n/ko/_posts/2023/2023-11-26-vite-5-node.js-20.10.0esm-state-of-js.md
=> translate: 20231126 article

_i18n/ko/_posts/2023/2023-12-01-node.js-v18.19.0lts-biomeprettier-css-hooks.md
=> translate: 20231201 article

_i18n/ko/_posts/2023/2023-12-08-redux-5.0.0-vitest-1.0.0-astro-4.0.md
=> translate: 20231208 article

_i18n/ko/_posts/2023/2023-12-23-date-fns-3.0.0-firefox-121-react-aria-components-1.0.0-catalyst.md
=> translate: 20231223 article

_i18n/ko/_posts/2024/2024-01-11-biome-v1.5-node.js-v20.11.0-rspack-0.5.md
=> translate: 20240111 article

_i18n/ko/_posts/2024/2024-01-16-jser-13th.md, _i18n/ko/_posts/about/2015-06-10-about.md
=> translate: 13th anniversary & about jser

_i18n/ko/_posts/2024/2024-01-21-astro-4.2-bun-1.0.24bun-shell-remixspa.md
=> translate: 20240121 article

_i18n/ko/_posts/2024/2024-01-28-firefox-122-deno-1.40-safari-17.4-beta.md
翻訳しました。
個人的感想ですがFirefoxリリースとかは凄くうれしいですね。:)
=> translate: 20240128 article

_i18n/ja/_posts/2024/2024-02-05-typescript-5.4-beta-learn-testingperformance-interop-2024.md, _i18n/ko/_posts/2024/2024-02-05-typescript-5.4-beta-learn-testingperformance-interop-2024.md
=> translate: 2024-02-05 article

_i18n/ko/_posts/2024/2024-02-12-jquery-4.0.0-storybook-8-beta-vite-5.1runtime-api.md
=> translate: 20240212 article

_i18n/ko/_posts/2024/2024-02-20-es2024-rc-typescript-eslint-v7-react-compiler.md
=> translate: 2024-02-20 article

_i18n/ko/_posts/2024/2024-02-27-firefox-123-remix-2.7.0remix-vite-is-stable-2023node.js.md
=> translate: 20240227 article

_i18n/ko/_posts/2024/2024-03-05-parcel-v2.12.0-polyfill.io-express-4.18.3.md
=> translate(article): 2024-03-05

_i18n/ko/_posts/2024/2024-03-19-storybook-8-nuxt-3.11-cloudflare-workers-vitest.md
=> translate(article): 20240319

_i18n/ko/_posts/2024/2024-03-27-firefox-124-chrome-123-node.js.md
=> translate(aritcle): 20240327

_i18n/ko/_posts/2024/2024-04-02-gulp-5.0.0-deno-1.42-bun-1.1windows.md
=> translate: 2024-04-02 article

_i18n/ko/_posts/2024/2024-04-11-zx-8.0.0-eslint-9.0.0-flowcomponent.md
=> translate: 2024-04-11

_i18n/ja/_posts/2024/2024-04-11-zx-8.0.0-eslint-9.0.0-flowcomponent.md
=> fix: fixed broken link

_i18n/ko/_posts/2024/2024-04-18-next.js-v14.2-farm-v1.0-biome-v1.7-pnpm-v9.md
=> translate: 2024-04-18

_i18n/ko/_posts/2024/2024-05-03-bun-v1.1.5cross-compile-react-18.3.0-svelte-5-rc.md
=> translate: 2024-05-03 article

_i18n/ko/_posts/2024/2024-05-12-headless-ui-v2.0-for-react-astro-v4.8-node.js.md
=> translate: 2024-05-12 article

_i18n/ko/_posts/2024/2024-05-19-remix-react-router-react-router-state-of-html-2023.md
=> translate: 2024-05-19

_i18n/ko/_posts/2024/2024-05-26-next.js-15-rc-solidstart-1.0-angular-v18zoneless.md
=> translate: 2024-05-26

_i18n/ko/_posts/2024/2024-06-03-vitest-v2.0.0-beta.5browser-mode-rspack-v0.7-eslint-migrator.md
=> translate: 2024-06-03

_i18n/ko/_posts/2024/2024-06-13-storybook-8.1-turborepo-2.0-node-v22.3.0snapshot-testing.md
=> translate: 2024-06-13 article

_i18n/ko/_posts/2024/2024-06-22-nuxt-2-eol-typescript-5.5-state-of-javascript-2023.md
翻訳しました。
仕事の関係でNode-RED4.0は興味深いです。👻
=> translate: 2024-06-22

_i18n/ko/_posts/2024/2024-07-01-es2024-playwright-v1.45.0-e18eecosystem-performance.md
=> translate: 2024-07-01 article

_i18n/ko/_posts/2024/2024-07-11-esbuild-v0.220.23-node.js-22.4.0-pnpm-9.5-catalogs.md
=> translate: 2024-07-11 article

_i18n/ko/_posts/2024/2024-07-18-700-vitest-2.0.0-node.js-22.5.0sqlite-private-browsing-mode.md
=> translate: 2024-07-18 article

_i18n/ko/_posts/2024/2024-07-29-typescript-5.6-beta-node.jstypescript-state-of-react-2023.md
=> translate: 2024-07-29 article

_i18n/ko/_posts/2024/2024-08-06-typescript-eslint-v8-jquery-ui-1.14.0ie-porffor.md
=> translate: 2024-08-06 article

_i18n/ko/_posts/2024/2024-08-15-node-v22.6.0-experimental-strip-types-firefox-129-.md
=> translate: 2024-08-15 article

_i18n/ko/_posts/2024/2024-08-25-webdriverio-v9-node-v22.7.0ts-enumnamespace-deno-1.46last-1.x.md
=> translate: 2024-08-25 article

_i18n/ko/_posts/2024/2024-09-01-rspack-1.0-safari-technology-preview-202-material-ui-v6.md
=> translate: 2024-09-01 article

_i18n/ko/_posts/2024/2024-09-09-vue-3.5-jsprimer-v6-a11y-visualizer.md
翻訳しました。
JavaScript Primer@v6おめでとうございます。😄
=> translate: 2024-09-09 article

_includes/head.html, public/js/external-links-new-tab.js
resolved https://github.com/jser/jser.info/issues/121
=> open external links in new tab

_i18n/ko/_posts/2024/2024-09-23-date-fns-v.4.0.0timezone-deno-2.0-rc-safari-18.0.md
=> translate: 2024-09-24 article

_i18n/ja/_posts/2024/2024-09-23-date-fns-v.4.0.0timezone-deno-2.0-rc-safari-18.0.md
=> fix(typo): 2024-09-23 article

_i18n/ko/_posts/2024/2024-10-29-svelte-5-msw-v2.6.0websockets-api-state-of-css-2024.md
=> translate: 2024-10-29 article

_i18n/ko/_posts/2024/2024-11-07-node-v22.11.0-lts-nuxt-3.14-vlt-package-manager-.md
=> translate: 2024-11-07 article

_i18n/ko/_posts/2024/2024-12-04-node.js-v22.12.0-vite-6.0-tailwind-css-v4.0-beta-1.md
=> translate: 2024-12-04 article

_i18n/ko/_posts/2024/2024-12-11-react-v19-astro-v5-the-2024-web-almanac.md
=> translate: 2024-12-11 article

_i18n/ko/_posts/2024/2024-12-19-safari-18.2-state-of-node.js-performance-2024-astro-server-islands.md
=> translate: 2024-12-19 article

_i18n/ja/_posts/2024/2024-12-28-pnpm-10.0-rc.1-state-of-javascript-2024-design-token-based-ui-architecture.md, _i18n/ko/_posts/2024/2024-12-28-pnpm-10.0-rc.1-state-of-javascript-2024-design-token-based-ui-architecture.md
=> translate: 2024-12-28 article

_i18n/ko/_posts/2025/2025-01-09-pnpm-10-node-v23.6.0-experimental-strip-types-e18e.md
=> translate: 2025-01-09 article

_i18n/ko/_posts/2025/2025-01-16-wintertc-tc55-node.jstypescript-angular-2025.md
=> translate: 2025-01-16 article

_i18n/ko/_posts/2025/2025-01-23-vitest-3.0-rspack-1.2-react-server.md
=> translate: 2025-01-23 article

_i18n/ko/_posts/2025/2025-02-01-bun-1.2-tailwind-css-v4.0-typescript-5.8-beta.md
翻訳しました。
最近、会社のプロジェクトのBarrel Patternが悩ましいところたったので[eslint-plugin-no-barrel-filesを導入してBarrel filesをやめた話](https://developers.prtimes.jp/2025/01/28/avoid-barrel-files-in-prtimes/)記事はすごく興味深かったです。😄
=> translate: 2025-02-01 article

_i18n/ko/_posts/2025/2025-02-14-node.js-v22.14.0-prettier-v3.5.0-chrome-133.md
=> translate: 2025-02-14 article

_i18n/ko/_posts/2025/2025-02-24-create-react-app-deno-2.2-bun-1.2.3-eslintcss.md
=> translate: 2025-02-24 article

_i18n/ko/_posts/2025/2025-03-06-typescript-5.8erasablesyntaxonly-next.js-15.2-lynx.md
=> translate: 2025-03-06 article

_i18n/ko/_posts/2025/2025-03-25-node.js-v20.19.0-valibot-v1-css-relative-colors.md
=> translate: 2025-03-25 article

_i18n/ko/_posts/2025/2025-04-03-next.js-lts-policy-rsdoctor-1.0-zxlite.md
=> translate: 2025-04-03 article

_i18n/ko/_posts/2025/2025-04-17-zod-4-beta-next.js-15.3rspack-llm.md
=> translate: 2025-04-17 article

_i18n/ko/_posts/2025/2025-04-27-node-v22.15.0-react-node.jsv8-gc.md
=> translate: 2025-04-27 article

_i18n/ko/_posts/2025/2025-05-07-koa-v3.0.0-node.js-24node.js-18-eol-allfunctionscalledonload.md
=> translate: 2025-05-07 article

_i18n/ko/_posts/2025/2025-05-09-jser-mcp.md
=> translate: 2025-05-09 article

_i18n/ko/_posts/2025/2025-05-20-zod-4-use-client-fresh-2-roadmap.md
=> translate: 2025-05-20 article

_i18n/ko/_posts/2025/2025-05-29-typescript-native-previews-firefox-139-angular-20-chrome-137.md
=> translate: 2025-05-30

_i18n/ko/_posts/2025/2025-06-06-rolldown-vite-vite-3.2-react-routergovernance-model.md
=> translate: 2025-06-06 article

_i18n/ko/_posts/2025/2025-06-15-safari-26-beta-pnpm-10.12-jest-30.md
=> translate: 2025-06-15 article

_i18n/ko/_posts/2025/2025-06-26-biome-v2-vite-7.0-chrome-138-firefox-140.md
=> translate: 2025-06-26 article

_i18n/ko/_posts/2025/2025-07-04-ecmascript-2025-rspack-1.4-deno-2.4-bundle-size.md
=> translate: 2025-07-04 article

_i18n/ko/_posts/2025/2025-07-31-nuxt-3.18-bun-v1.2.19-svg.md
=> translate: 2025-07-31 article

_i18n/ko/_posts/2025/2025-08-07-node.js-v22.18.0-lts-typescript-5.9-panda-css-v1.md
=> translate: 2025-08-07 article

_i18n/ko/_posts/2025/2025-09-15-pnpm-10.16-deno-2.5-bun-install.md
=> translate: 2025-09-15 article
