_posts/2015/2015-04-20-es6-final-draft-js-traning.md
「[2015-04-20のJS](http://jser.info/2015/04/20/es6-final-draft-js-traning/)」の React の項目の周辺のレイアウトが他と揃っていなかったようなので修正しました。
=> fix layout

_includes/google_analytics.html
Replace google analytics script with https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#alternativeSnippet 
`<scirpt async>` provide real async loading.
Before: (analytics.js was blocked by CSS downloading)
After:
- [Script-injected &#34;async scripts&#34; considered harmful - igvita.com](https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/ "Script-injected &#34;async scripts&#34; considered harmful - igvita.com") ([ja](http://postd.cc/script-injected-async-scripts-considered-harmful/))
- [Chromium Blog: New JavaScript techniques for rapid page loads](http://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html "Chromium Blog: New JavaScript techniques for rapid page loads") ([Chrome で高速にページを読み込む新しい技術のご紹介 - Google …
=> Update google analytics async script

_posts/2015/2015-06-02-Angular1.4.0-Polymer1.0.md
「[2015-06-02のJS](http://jser.info/2015/06/02/Angular1.4.0-Polymer1.0/)」の「[Moving to ES6 from CoffeeScript](http://jser.info/2015/06/02/Angular1.4.0-Polymer1.0/#moving-to-es6-from-coffeescript)」は、「[2015-05-27のJS](http://jser.info/2015/05/27/promise-angular2/)」で[既に紹介されています](http://jser.info/2015/05/27/promise-angular2/#moving-to-es6-from-coffeescript)ので、不要と思われる「2015-06-02のJS」の方を削除してみました。
=> remove an already introduced entry

_i18n/ja.yml, _i18n/ja/_posts/about/2015-06-10-about.md, _i18n/ko.yml, _i18n/ko/_posts/about/2015-06-10-about.md, about.md
#93 に関連するaboutページの修正です。
`title: page.title` の翻訳がプラグインの仕組み的に難しいため、`about.md`をpage typeからpost typeに変更しました。
- URL自体は同じで、記事ファイル自体にtitleを直接書くように変更しました
- 通常の記事と同じlayout:postに変更
page typeは殆ど使ってないので、aboutページだけのために色々工夫するよりは([Multiple Languages in Jekyll](https://github.com/screeninteraction/jekyll-multiple-languages-plugin "Multiple Languages in Jekyll")的にも難しそう)、通常の記事と同じ仕組で翻訳すると問題が少なくて良いと思います。
Before:
`<title>` 要素の中身にkeyそのものが表示されてしまってる
After: 
/cc @UYEONG
=> fix(page): aboutページをpageからpostへ変更

_i18n/ja/_posts/2015/2015-07-28-title.md
ページと Service Worker の間での postMessage は以前からできていましたが、今回のバージョンアップでページから Service Worker へ postMessage したときのメッセージ配送先が window から navigator.serviceWorker に変更されました。
=> Revise the summary about ServiceWorker changes

_i18n/ja/_posts/2015/2015-12-07-jasmine2.4-redux-firefox.md
*airbnb/reagent* -> *airbnb/enzyme*
名前変更されてるのでリダイレクトはされますが…
=> Change: change repository name & url

_i18n/ja/_posts/2016/2016-01-20-jquery3beta-esnext-news-chkracore.md
「[ES.next News: The 5 best ECMAScript links of the week](http://esnextnews.com/)」の項目の関連リンクについて、項目のリンクと重複していると思われるリンクがありましたので修正しました。
=> fix a duplicated link

_i18n/ja/_posts/2016/2016-01-27-math.random-xsfhit.md
- [Update Math.random to use xorshift128+ by suwc · Pull Request #145 · Microsoft/ChakraCore](https://github.com/Microsoft/ChakraCore/pull/145 "Update Math.random to use xorshift128+ by suwc · Pull Request #145 · Microsoft/ChakraCore")
- [V8 JavaScript Engine: There's Math.random(), and then there's Math.random()](http://v8project.blogspot.jp/2015/12/theres-mathrandom-and-then-theres.html)
- [322529 – Upgrade Math.random() to the better XorShift128+ algorithm](https://bugzilla.mozilla.org/show_bug.cgi?id=322529)
- [Math.random() and 32-bit precision](http://jandemooij.nl/blog/2015/11/27/math-random-and-32-bit-precision/)
- [Bug 151641 – Use a better RNG for Math.random()](https://bugs.webkit.org/show_bug.cgi?id=151641)
- [Google Chromeが採用した、擬似乱数生成アルゴリズム「xorshift」の数理 – …
=> Math.randomのアルゴリズム XorShift128+

_i18n/ja/_posts/2016/2016-06-21-ecmascript2016-unit2.0.md, _i18n/ja/_posts/2016/2016-06-21-title.md
- [ECMAScript 2016の言語仕様をECMA Internationalが承認。正式版として公開 － Publickey](http://www.publickey1.jp/blog/16/ecmascript_2016ecma_international.html)
- [Standard ECMA-262](http://www.ecma-international.org/publications/standards/Ecma-262.htm)
- [Release 3rd Edition - Release Candidate · tc39/ecma402](https://github.com/tc39/ecma402/releases/tag/3.0-rc-1)
- [ECMAScript® 2016 Language Specification](http://www.ecma-international.org/ecma-262/7.0/#sec-overview)
- [Release 2.0.0 · jquery/qunit](https://github.com/jquery/qunit/releases/tag/2.0.0)
- [実例とともに学ぶECMAScript 2015 〜Generator〜 – NET BIZ DIV. TECH BLOG](https://tech.recruit-mp.co.jp/front-end/post-10358/)
=> 2016-06-21のJavaScript

_i18n/ja/_posts/2016/2016-06-27-babel-6110safari-tp7firefox-49.md
- [Release v6.11.0 · babel/babel](https://github.com/babel/babel/releases/tag/v6.11.0)
- [Developer Edition 49: Network Request Stack Traces and more ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/06/developer-edition-49-network-request-stack-traces-and-more/)
- [JavaScript error reference - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors)
- [Release Notes for Safari Technology Preview Release 7 | WebKit](https://webkit.org/blog/6640/release-notes-for-safari-technology-preview-release-7/)
=> 2016-06-27のJavaScript

_i18n/ja/_posts/2016/2016-07-04-d3-400servo-nightlyecmascript-as-a-living-standard.md
- [Release v4.0.0 · d3/d3](https://github.com/d3/d3/releases/tag/v4.0.0)
- [Servo Nightly Builds Available](https://blog.servo.org/2016/06/30/servo-nightlies/)
- [servo/servo: The Servo Browser Engine](https://github.com/servo/servo)
- [Node学園 21時限目でECMAScript as a Living Standardという発表をした | Web Scratch](http://efcl.info/2016/06/29/node-ecmascript/)
- [ECMAScript as a Living Standard](http://azu.github.io/slide/2016/node-es/ecmascript.html)
=> 2016-07-04のJavaScript

_i18n/ja/_posts/2016/2016-08-15-chrome-53-beta60fps-css-animation.md
[元の記事](https://rainsoft.io/make-your-javascript-code-shide-knockout-old-es5-hack/#1verifytheelementexistenceinanarray)にも記載ありますが`Array.prototype.includes`はES 2016以降に策定されたものです。
周辺の部分を含めて即した文書に書き換えました。
=> `Array.prototype.includes`が策定された時期をES 2016以降に修正

_i18n/ja/_posts/2016/2016-10-24-npm-4.0.0-node.js-v6.9.0-lts-webpack2.md
- [Release v4.0.0 · npm/npm](https://github.com/npm/npm/releases/tag/v4.0.0)
- [node-gakuen-201610.md](https://gist.github.com/othiym23/c98bd4ef5d9fb3f496835bd481ef40ae)
- [Node v6.9.0 (LTS) | Node.js](https://nodejs.org/en/blog/release/v6.9.0/)
- [Node.js v6 Transitions to LTS – Medium](https://medium.com/@nodejs/node-js-v6-transitions-to-lts-be7f18c17159#.c8d2tljbn)
- [webpack](https://webpack.js.org/how-to/upgrade-from-webpack-1/)
- [TestCafeでブラウザの自動テスト(E2Eテスト) | Web Scratch](http://efcl.info/2016/10/23/testcafe/)
- [Migrating to Webpack 2](http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/)
=> 2016-10-24のJavaScript

_i18n/ja/_posts/2016/2016-11-01-node.js-v7-node.js-v0.10-eol-webassembly-browser-preview.md
Node
- [Node v7.0.0 (Current) | Node.js](https://nodejs.org/en/blog/release/v7.0.0/)
- [Node v7 で入った WHATWG URL 実装について | blog.jxck.io](https://blog.jxck.io/entries/2016-10-27/whatwg-url.html)
- [nodejs/LTS: Node.js Foundation Long-term Support Working Group](https://github.com/nodejs/LTS)
wasm
- [V8 JavaScript Engine: WebAssembly Browser Preview](http://v8project.blogspot.jp/2016/10/webassembly-browser-preview.html)
- [WebKit Feature Status | WebKit](https://webkit.org/status/#specification-webassembly)
- [WebAssembly Browser Preview ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/10/webassembly-browser-preview/)
- [WebAssembly](http://webassembly.org/community/feedback/)
- [A peek into the WebAssembly Browser Preview | Microsoft Edge Dev …
=> 2016-11-01のJavaScript

_i18n/ja/_posts/2016/2016, _i18n/ja/_posts/2016/2016-12-27-sharedarraybuffer-javascript-obfuscator-node.js-stream.md
- [ECMAScript Shared Memory and Atomics](http://tc39.github.io/ecmascript_sharedmem/shmem.html#GlobalObject.ConstructorProps.SharedArrayBuffer)
- [tc39/ecmascript_sharedmem: Shared memory and atomics for ECMAscript](https://github.com/tc39/ecmascript_sharedmem)
- [tc39/ecmascript_sharedmem: Shared memory and atomics for ECMAscript](https://github.com/tc39/ecmascript_sharedmem)
- [A Taste of JavaScript’s New Parallel Primitives ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2016/05/a-taste-of-javascripts-new-parallel-primitives/)
- [20161113-nodefest // Speaker Deck](https://speakerdeck.com/chikoski/20161113-nodefest)
- [SharedArrayBufferとAtomics APIについて - JS.next](http://js-next.hatenablog.com/entry/2015/09/30/225251)
----
- [highWaterMarkから探るNode.jsのStreamの仕組み - …
=> 2016-12-27のJavaScript

_i18n/ja/_posts/2017/2017-05-03-headless-chromefirefoxphantomjsslimerjs-es-modules.md
https://www.amazon.co.jp/Web%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89-%E3%83%8F%E3%82%A4%E3%83%91%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%B3%E3%82%B9-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0-%E4%B9%85%E4%BF%9D%E7%94%B0-%E5%85%89%E5%89%87/dp/4774189677
https://www.kinokuniya.co.jp/f/dsg-01-9784774189673
技術評論社のサイト上では確認できなかったのですが、登録されている情報では2日ではなく、26日のようでした。
=> 発売日を 5月26日 に修正

_includes/sidebar.html
検索フォームをクリックすると Slack のページに飛ばされます。
「Slack に RSS を追加する」リンクの閉じタグがないようです。
=> Fix slack link

_i18n/ja/_posts/2019/2019-06-10-mathjs-v6modern-javascriptaudits-in-web-inspector.md
`--experimental-modules` が有効になっている場合、 (ブラウザ側に合わせて)常にJSOM moduleが有効になったため、不要になった `--experimental-json-modules` フラグは削除されています。
=> --experimental-json-modules フラグは削除されています

_i18n/ja/_posts/2020/2020-07-28-sveltetypescript-chrome-85-beta-web-speed-hackathon-online.md
=> fix: typo in 2020-07-28-sveltetypescript-chrome-85-beta-web-speed-hackathon-online.md

_i18n/ja/_posts/2021/2021-02-02-webrtc-1.0-firefox-85-chrome-89-beta.md
> ES Proposal Stage 3のTop-Level awaitのサポート、at()メソッドのサポートなどが追加されています。
とありますが、これは間違いです。Firefox 85.0.1で`[ 0,1,2,3,4 ].at(1)`を実行すると`Uncaught TypeError: [...].at is not a function`となります。
[**Firefox 85 for developers - Mozilla | MDN**](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/85) にも載っていません。
Mozilla Hacks の [**January brings us Firefox 85**](https://hacks.mozilla.org/2021/01/january-brings-us-firefox-85/) にこの2つが書かれていて紛らわしいですが、恐らくその前のこの文を見落とされたのだと思います。  
> ## Nightly previews
> There are a couple of upcoming additions to Gecko that are currently available only in our Nightly Preview.
=> Firefox 85についての情報の修正

_i18n/ja/_posts/2022/2022-02-14-parcel-2.3.0-vite-2.8.0-angular-compiler-javascriptddd.md
実装はされたんですが、フラグがついているもので、リリースされてはいないです。
MDNのほうでも項目が削除されています。
https://github.com/mdn/content/pull/12969
=> fix(2022-02-14): Firefox 97の項目からscroll-timelineの言及を削除

_i18n/ja/_posts/2022/2022-04-26-redux-v4.2.0-node.js-18-jest-28.md
```
Jes 28がリリースされました。
```
↓
```
Jest 28がリリースされました。
```
=> 「2022-04-26のJS: Redux v4.2.0、Node.js 18、Jest 28」内のタイポ修正PRです

_i18n/ja/_posts/2022/2022-06-01-lerna-5.0.0-typescript-4.7-wireit.md
```html
<h2 id="ember-4-4-released">Ember 4.4 Released</h2>
<p><a href="https://blog.emberjs.com/ember-released-4-4/" title="Ember 4.4 Released">blog.emberjs.com/ember-released-4-4/</a><br>
<p class="jser-tags jser-tag-icon"><span class="jser-tag">Ember</span> <span class="jser-tag">ReleaseNote</span></p></p>
<p>Ember 4.4リリース。<br>
`<code>の有効化、</code>ember generate<code>で生成されるテストテンプレートのモジュールを変更可能に、</code>hasListeners`を公開APIに変更など</p>
<hr>
```
```html
<h2 id="ember-4-4-released">Ember 4.4 Released</h2>
<p><a href="https://blog.emberjs.com/ember-released-4-4/" title="Ember 4.4 Released">blog.emberjs.com/ember-released-4-4/</a><br>
<p class="jser-tags jser-tag-icon"><span class="jser-tag">Ember</span> <span class="jser-tag">ReleaseNote</span></p></p>
<p>Ember 4.4リリース。<br> …
```
=> 意図せずliquidテンプレートタグとして認識されていた部分をエスケープ

_i18n/ja/_posts/2023/2023-02-15-lighthouse-10-core-js-webcontainers.md, _i18n/ko/_posts/2023/2023-02-15-lighthouse-10-core-js-webcontainers.md
`StroyObj` → `StoryObj` に修正しました。
参考文献: https://storybook.js.org/docs/react/api/csf
=> Fixed typo `StroyObj` → `StoryObj`

_i18n/ja/_posts/2023/2023-04-30-vite-4.3-deno-1.33-node.js-1418.md
`リフレットレート` → `リフレッシュレート` に修正しました。
=> Fix typo(リフレットレート→リフレッシュレート)

_i18n/ja/_posts/2023/2023-12-15-safari-17.2-deno-1.39webgpu-sveltekit-2.md, _i18n/ko/_posts/2023/2023-12-15-safari-17.2-deno-1.39webgpu-sveltekit-2.md
=> translate: 20231215 article

_i18n/ja/_posts/2024/2024-01-02-vue-3.4-vue-2.xeol-quick-lint-js-3.0.0-astrodeno2023.md, _i18n/ko/_posts/2024/2024-01-02-vue-3.4-vue-2.xeol-quick-lint-js-3.0.0-astrodeno2023.md
=> translate: 20240102 article

_i18n/ja/_posts/2024/2024-04-26-electron-30-firefox-125-node.js-22-react-19-beta-typescript-5.5-beta.md, _i18n/ko/_posts/2024/2024-04-26-electron-30-firefox-125-node.js-22-react-19-beta-typescript-5.5-beta.md
=> translate: 2024-04-26 article

_i18n/ko/_posts/2024/2024-10-01-oxc-transformer-alpha-node.js9-express-5.0-pre-release.md
=> translate: 2024-10-01 article

_i18n/ko/_posts/2024/2024-10-08-webplatform-node-v20.18.0networkinspect-stylex-0.8.0.md
=> translate: 2024-10-08 article

_i18n/ko/_posts/2024/2024-11-26-angular-v19-deno-2.1lts-react-router-v7from-remix.md
=> translate: 2024-11-26 article

_i18n/ja/_posts/2025/2025-01-23-vitest-3.0-rspack-1.2-react-server.md, _i18n/ko/_posts/2025/2025-01-23-vitest-3.0-rspack-1.2-react-server.md
どちらもlrになっていたので片方をrlに変更しました。
順番はChromeのBlogに合わせました。
> Support for [sideways-rl and sideways-lr](https://developer.mozilla.org/docs/Web/CSS/writing-mode#values) keywords for the writing-mode CSS property.
=> sideways-{lr,lr}をsideways-{rl,lr}に修正する

_i18n/ko/_posts/2025/2025-04-09-express-5.1-safari-18.4-eslint-bulk-suppressions.md
=> translate: 2025-04-09 article

_i18n/ja/_posts/2025/2025-05-25-jser-14th.md
I think it should be [Plugin System in Rust based JavaScript / TypeScript Linters](https://speakerdeck.com/unvalley/typescript-linters) instead of [Exploring Type-Informed Lint Rules in Rust based TypeScript Linters](https://speakerdeck.com/unvalley/exploring-type-informed-lint-rules-in-rust-based-linters)
Anyway thanks for the reference, and congrats 14th anniversary!
=> Fix a slide link in `2025-05-25-jser-14th.md`

_i18n/ja/_posts/2025/2025-07-04-ecmascript-2025-rspack-1.4-deno-2.4-bundle-size.md
tz-lookupの主目的は「緯度経度からタイムゾーンを検索する」ものです。おおよその地名を知ることができるのはあくまでタイムゾーンと地名がある程度関連づいているからです。
=> 2025-07-04の記事の変更

_i18n/ko/_posts/2025/2025-08-21-next.js-15.5-rslintoxlint-jsprimer-v7.0.0es2025.md
翻訳しました。
js-primer v7.0.0、おめでとうございます。
=> translate: 2025-08-21 article
